version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - vipas_data:/var/lib/mysql
volumes:
  vipas_data: